# Generated by Django 4.2 on 2023-09-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='name',
            field=models.CharField(default='No Name', max_length=200),
        ),
    ]
